name = input("Type a name: ")
print(name)
place = input("Type a place: ")
print(place) 
verb = input("Type a verb: ")
print(verb)
noun = input("Type a noun: ")
print(noun) 
sentence = input(name)
print(sentence, " went to the ")
sentence = (sentence, place)
print(sentence, " where they ")
sentence = (sentence, verb)
print(sentence, " and bought a") 
sentence = (sentence, noun)
print(sentence, ".\n")
print(sentence)
print(f"{name} went to the {place} where they {verb}and bought a {noun} name, place, verb, noun")
print(f"{name} went to the {place} where he {verb} and bought a {noun}.", name, place, verb, noun)